[tox]
envlist =
    py{39,310,311,312,313}-lint,
    ruff-check,
    py{39,310,311,312,313}-Plone{60,61},
#    docs,
#    coverage-report,

skip_missing_interpreters = True


[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313


[gh-actions:env]
PLONE_VERSION =
    Plone60: Plone60
    Plone61: Plone61


[testenv]
skip_install = true

extras =
    develop
    test

commands =
    {envbindir}/buildout -q -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} bootstrap
#    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} annotate
    {envbindir}/buildout -n -qq -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} install test robot
    coverage run {envbindir}/test -v1 --auto-color {posargs}
    # coverage run {envbindir}/test -v --all -t robot {posargs}

setenv =
    COVERAGE_FILE=.coverage.{envname}
    Plone60: version_file=test_plone60.cfg
    Plone61: version_file=test_plone61.cfg

deps =
    Plone60: -rrequirements_plone60.txt
    Plone61: -rrequirements_plone61.txt
    coverage


[testenv:coverage-report]
skip_install = true
usedevelop = True
basepython = python3.11

deps =
    coverage
    -cconstraints_plone60.txt

setenv =
    COVERAGE_FILE=.coverage

commands =
    coverage erase
    coverage combine
    coverage html
    coverage xml
    coverage report


[lint]
skip_install = true

deps =
    -cconstraints.txt
    ruff

commands =
    ruff check {toxinidir}/src {toxinidir}/setup.py


[testenv:ruff-check]
basepython = python3.11
skip_install = True
deps =
    -cconstraints.txt
    ruff

commands =
    ruff check src setup.py
    ruff format --check --diff src setup.py


[testenv:ruff-fix]
basepython = python3.11
skip_install = True
deps =
    -cconstraints.txt
    ruff

commands =
    ruff check --fix src setup.py
    ruff format src setup.py


[testenv:py39-lint]
basepython = python3.9
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}

[testenv:py310-lint]
basepython = python3.10
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}

[testenv:py311-lint]
basepython = python3.11
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}

[testenv:py312-lint]
basepython = python3.12
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}

[testenv:py313-lint]
basepython = python3.13
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}

[testenv:docs]
skip_install = true

deps =
    Sphinx

commands =
    sphinx-build -b html -d _build/docs/doctrees docs _build/docs/html
